sudo: true
language: python
python:
  - "3.6"
branches:
  only:
    - develop
install:
  - pip install -r requirements.txt
script:
  - pytest app --cov --disable-warnings --ignore=app/tests
after_success:
  - coveralls
