sudo: true
language: python
python:
  - "3.6"
branches:
  only:
    - develop
install:
  - pip install pipenv
  - pipenv install
script:
  - pytest app --cov --disable-warnings
after_success:
  - coveralls
